### ISSUE TITLE
Issue when inserting a picture with autoform after modifying another parameter

### ISSUE THREAD

**Issue by marcoschwartz** [VeliovGroup/meteor-autoform-file#37] opened 2017-10-30 21:07 UTC
Hello,

I am having an issue that I actually had for a while now with meteor-autoform-file, so it's not related to the most recent version or to Meteor 1.6 (had the same with 1.5).

Basically when I use autoform to edit a document with a file in it, if I first edit the file and then some other parameters (like String, Number, etc), it's all file. However, whenever I first edit another parameter and then a file, even if the file is correctly uploaded and displayed on the screen, it won't be saved.

Also, in both cases I see this in the console on the client:

`Error: Unexpected object in htmljs in toText: [object Object]
    at HTMLVisitorSubtype.visitObject (htmljs.js?hash=1ac878018eee6c53ed1375dc7ee75fc6865666ae:292)
    at HTMLVisitorSubtype.visit (htmljs.js?hash=1ac878018eee6c53ed1375dc7ee75fc6865666ae:113)
    at Object.HTML.toText (htmljs.js?hash=1ac878018eee6c53ed1375dc7ee75fc6865666ae:668)
    at Object.Blaze._toText (blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2468)
    at Blaze.View.updateAttributes (blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1586)
    at blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1934
    at Function.Template._withTemplateInstanceFunc (blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3744)
    at blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1932
    at Object.Blaze._withCurrentView (blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2271)
    at viewAutorun (blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1931)`

Any idea what could be the issue?

**Comment by dr-dimitru** [comment] 2017-10-31 09:00
Hello @marcoschwartz ,

Are you using `afQuickField` or `quickForm`?

**Comment by marcoschwartz** [comment] 2017-10-31 10:37
Hello,

It actually occurs in both cases

**Comment by dr-dimitru** [comment] 2017-10-31 12:55
@marcoschwartz do you have a link to autoForm developer's API? It's always a pain to debug and work with autoForm as plugin developer.

**Comment by marcoschwartz** [comment] 2017-11-01 20:32
Hello, unfortunately I don't, never developed with it. Maybe I should open a ticket there as well?

**Comment by dr-dimitru** [comment] 2017-11-05 22:30
@marcoschwartz not sure about opening a ticket at AF rep.
But if someone experienced with AF could help us to change current flow to uploading and updating files after form us submitted instead of current upload upon file selection - this will be great.

**Comment by abmar** [comment] 2018-01-15 15:58
I got the same annoying behavior with 

> Error: Unexpected object in htmljs in toText: [object Object] at  ...

and at some moment the hidden input field doesnt change at all even in case of removal or new upload.
I guess the Exception that arises, comes from the constraint {{#if Template.subscriptionsReady }} that wraps the autoform. hence, my workaround about that, to get rid of the above exception, was to issue reactively a new subscription each time the form get submitted, saved and the new image field returned as a changed event. 
This way the rendering is constrained to wait for the new subscription readiness and no exception arises anymore. It worked for me, and hope it will help ... until a cleaner fix would be available ...

**Comment by marcoschwartz** [comment] 2018-01-15 18:26
@abmar Interesting! So what exactly did you do to fix the issues, like which files you had to modify?

**Comment by abmar** [comment] 2018-01-15 19:48
@marcoschwartz as I said the only thing I did, was an workaround consisting to issue a new subscription each time the form is submitted and the related document saved/updated.
I followed exactly what the documentation suggests for schema , collection ... declarations, and in my template's onCreated hook I did the following:
```javascript
Template.profile.onCreated(function() {
  this.autorun(() => {
    user = this.data && this.data.user || Meteor.user(); //edit current user or another passed one (admin)
    user = user ? Users.find({
      _id: user._id
    }).fetch()[0] : undefined;
    this.subscribe("users.userData", user && user._id, user && user.picture); //avoid triggering tracker exception
  });
})
```

**Comment by dr-dimitru** [comment] 2018-03-02 12:04
> But if someone experienced with AF could help us to change current flow to uploading and updating files after form is submitted, instead of current upload upon file selection - this will be great.

All we need is to find a hook in AF API to upload a file when form submitted (something like: `onSubmit`), not when the file is selected.

Hopefully Eric (@aldeed) can help us here. 

//cc @mksh-su @abmar @marcoschwartz

**Comment by ankitv89** [comment] 2019-02-14 12:48
@dr-dimitru I am getting a similar error when using `insertConfig` to manage meta data. Any Advice on how to overcome this? The file is getting inserted in the Files Collection and even uploaded to s3, but the field is null in the document send to the server.

**Comment by jankapunkt** [comment] 2019-02-15 13:27
@ankitv89 can you provide a minimal example repo which I can clone to reproduce? Then I will check into it and see if I can fix it.

**Comment by ankitv89** [comment] 2019-02-19 10:08
> @ankitv89 can you provide a minimal example repo which I can clone to reproduce? Then I will check into it and see if I can fix it.

I will get back to you with this in a week. Thanks.

**Comment by dr-dimitru** [comment] 2019-06-29 10:26
Friendly ping for @ankitv89 @marcoschwartz @jankapunkt 
Feel free to close it in case if the issue is solved on your end. If not, lets keep discussion ;)

**Comment by dorw123** [comment] 2019-06-30 21:05
Hello... I`m also having the same issue. 

Exception from Tracker recompute function:

Error: Unexpected object in htmljs in toText: [object Object]
    at HTMLVisitorSubtype.visitObject (htmljs.js?hash=c52d96e73a36896980b68a9b66c659292f8e393f:292)
    at HTMLVisitorSubtype.visit (htmljs.js?hash=c52d96e73a36896980b68a9b66c659292f8e393f:113)
    at Object.HTML.toText (htmljs.js?hash=c52d96e73a36896980b68a9b66c659292f8e393f:668)
    at Object.Blaze._toText (blaze.js?hash=51f4a3bdae106610ee48d8eff291f3628713d847:2468)
    at Blaze.View.updateAttributes (blaze.js?hash=51f4a3bdae106610ee48d8eff291f3628713d847:1586)
    at blaze.js?hash=51f4a3bdae106610ee48d8eff291f3628713d847:1934
    at Function.Template._withTemplateInstanceFunc (blaze.js?hash=51f4a3bdae106610ee48d8eff291f3628713d847:3769)
    at blaze.js?hash=51f4a3bdae106610ee48d8eff291f3628713d847:1932
    at Object.Blaze._withCurrentView (blaze.js?hash=51f4a3bdae106610ee48d8eff291f3628713d847:2271)
    at viewAutorun (blaze.js?hash=51f4a3bdae106610ee48d8eff291f3628713d847:1931)

**Comment by jankapunkt** [comment] 2019-06-30 22:01
@dorw123 would you mind to provide a minimal repo for reproducing the issue? If I can reproduce it, chances are high that it can be fixed very quick.

**Comment by dorw123** [comment] 2019-07-01 06:31
> @dorw123 would you mind to provide a minimal repo for reproducing the issue? If I can reproduce it, chances are high that it can be fixed very quick.

Sure. I`ll make one asap and add a link here.

**Comment by dorw123** [comment] 2019-07-04 11:07
Hello @jankapunkt . Any progress so far ?

**Comment by jankapunkt** [comment] 2019-07-04 11:45
Woa, sorry! Just realized that I oversaw your comment with the link. I am just checking it out. Will get you back in a few hours.

**Comment by dorw123** [comment] 2019-07-04 12:04
> Woa, sorry! Just realized that I oversaw your comment with the link. I am just checking it out. Will get you back in a few hours.

Don`t worry mate. I just manage to solve the issue. It seems like putting 
```
insertConfig: { 
          meta: {},
          isBase64: false,
          transport: 'ddp',
          streams: 'dynamic',
          chunkSize: 'dynamic',
          allowWebWorkers: true
        }
```
inside the collection, it breaks the atts of the hidden input inside the afFileUpload template. 
Removing insertConfig from collection solves the issue.

**Comment by dorw123** [comment] 2019-07-04 12:08
Now, if you need special config, it`s just a matter of how do you set your config.

**Comment by jankapunkt** [comment] 2019-07-04 14:00
@dorw123 thanks a lot for pointing in this direction I finally found the source if the bug. If will provide a PR where I explain it.

// @dr-dimitru good news here

**Comment by jankapunkt** [comment] 2019-07-04 14:13
@marcoschwartz @abmar @ankitv89 @dorw123 

PR is ready: #54 

please check it out and give me feedback if anything still doesn't work.

**Closed** 2019-07-04 17:32 UTC
Labels: bug, help wanted
