### ISSUE TITLE
Request: Will there be an upgrade to aldeed:autoform@7.0.0?

### ISSUE THREAD

**Issue by sebastianspiller** [veliovgroup/meteor-autoform-file#60] opened 2021-01-22 11:28 UTC
At the moment, its constraint is aldeed:autoform@6.3.0.

**Comment by dr-dimitru** [comment] 2021-02-04 23:22
@sebastianspiller sorry for delay.
Please try [`v2.4.0`](https://github.com/veliovgroup/meteor-autoform-file/releases/tag/2.4.0)

Feel free to close it in case if the issue is solved on your end.

**Closed** 2021-03-09 20:18 UTC
Labels: question
